<?php

/**
 * ThanhHua Styleguide
 *
 * @author    Thanh Hua <thanh.hua@balanceinternet.com.au>
 * @copyright Balance Internet Pty Ltd (https://www.balanceinternet.com.au)
 */

declare(strict_types=1);

/** @var \ThanhHua\StyleGuide\Block\Section $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \ThanhHua\StyleGuide\ViewModel\ColorsProvider $viewModel */
$viewModel = $block->getViewModel();
$colors = $viewModel->getColors();
?>
<?php if (!empty($colors)): ?>
    <ul class="style-guide-colors">
        <?php foreach ($colors as $color): ?>
            <li class="style-guide-color style-guide-color-<?= $escaper->escapeHtmlAttr($color->getCode()) ?>">
                <span class="style-guide-color-visualization"></span>
                <span class="style-guide-color-name" title="<?= $escaper->escapeHtmlAttr($color->getLabel()) ?>"><?= $escaper->escapeHtml($color->getLabel()) ?></span>
                <span class="style-guide-color-css-color"><?= $escaper->escapeHtml($color->getCssColor()) ?></span>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
