<?php

/**
 * ThanhHua Styleguide
 *
 * @author    Thanh Hua <thanh.hua@balanceinternet.com.au>
 * @copyright Balance Internet Pty Ltd (https://www.balanceinternet.com.au)
 */

declare(strict_types=1);

/** @var \ThanhHua\StyleGuide\Block\Section $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \ThanhHua\StyleGuide\ViewModel\IconsProvider $viewModel */
$viewModel = $block->getViewModel();
$icons = $viewModel->getIcons();
?>
<?php if (!empty($icons)): ?>
<ul class="style-guide-icons">
    <?php foreach ($icons as $icon): ?>
        <li class="style-guide-icon">
            <span class="style-guide-icon-visualization">
                <span class="<?= $escaper->escapeHtmlAttr($icon->getCssClass()) ?>"></span>
            </span>
            <span class="style-guide-icon-name" title="<?= $escaper->escapeHtmlAttr($icon->getName()) ?>"><?= $escaper->escapeHtml($icon->getName()) ?></span>
        </li>
    <?php endforeach; ?>
</ul>
<?php endif ?>
