<?php

/**
 * ThanhHua Styleguide
 *
 * @author    Thanh Hua <thanh.hua@balanceinternet.com.au>
 * @copyright Balance Internet Pty Ltd (https://www.balanceinternet.com.au)
 */

declare(strict_types=1);

/** @var \ThanhHua\StyleGuide\Block\Section $block */
/** @var \Magento\Framework\Escaper $escaper */

$layouts = [
    'One Column' => '*/layout/onecolumn',
    'Two Columns Left' => '*/layout/twocolumnsleft',
    'Two Columns Right' => '*/layout/twocolumnsright',
    'Three Columns' => '*/layout/threecolumns',
]
?>
<ul>
    <?php foreach ($layouts as $title => $path): ?>
        <li>
            <a href="<?= $escaper->escapeHtmlAttr($block->getUrl($path)) ?>"><?= $escaper->escapeHtml(__($title)) ?></a>
        </li>
    <?php endforeach; ?>
</ul>
