<?php

/**
 * ThanhHua Styleguide
 *
 * @author    Thanh Hua <thanh.hua@balanceinternet.com.au>
 * @copyright Balance Internet Pty Ltd (https://www.balanceinternet.com.au)
 */

declare(strict_types=1);

/** @var \ThanhHua\StyleGuide\Block\Section $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<p><a href="#"><?= $escaper->escapeHtml(__('Default link')) ?></a></p>
<p><a href="#" class="secondary"><?= $escaper->escapeHtml(__('Secondary link')) ?></a></p>
