<?php

/**
 * ThanhHua Styleguide
 *
 * @author    Thanh Hua <thanh.hua@balanceinternet.com.au>
 * @copyright Balance Internet Pty Ltd (https://www.balanceinternet.com.au)
 */

declare(strict_types=1);

/** @var \ThanhHua\StyleGuide\Block\Section $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<ul>
    <li>
        <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</span>
    </li>
    <li>
        <span>Nulla efficitur ut justo eget faucibus. Donec lectus risus, suscipit eu gravida vel, fringilla at leo. Morbi ornare nunc eu dolor pharetra cursus. Suspendisse orci nisl, ultrices non sagittis vitae.</span>
    </li>
    <li>
        <span>Praesent sagittis dapibus nibh.</span>
    </li>
</ul>
