<?php

/**
 * ThanhHua Styleguide
 *
 * @author    Thanh Hua <thanh.hua@balanceinternet.com.au>
 * @copyright Balance Internet Pty Ltd (https://www.balanceinternet.com.au)
 */

declare(strict_types=1);

/** @var \ThanhHua\StyleGuide\Block\Section $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<div class="block widget styleguide-sidebar-block">
    <div class="block-title">
        <strong role="heading" aria-level="2"><?= $escaper->escapeHtml(__('Sidebar element')) ?></strong>
    </div>
    <div class="block-content">
        <p>Lorem ipsum dolor sit amet</p>
    </div>
</div>
